name: Bot Cadeira360

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Ver estrutura
        run: |
          ls -la
          echo "----"
          ls -la fontes
          
        run: python bot.py
